#!/bin/bash

echo

echo 生成一百万条用户数据 ......

echo

date

echo

echo 生成 t_user_1m.sql ......

echo

echo > t_user_1m.sql

echo "SET GLOBAL sync_binlog=0;" >> t_user_1m.sql
echo "SET GLOBAL innodb_flush_log_at_timeout=0;" >> t_user_1m.sql
echo "SET GLOBAL innodb_flush_log_at_trx_commit=0;" >> t_user_1m.sql

echo "ALTER TABLE t_user AUTO_INCREMENT=1000001;" >> t_user_1m.sql

echo "ALTER TABLE t_user DISABLE KEYS;" >> t_user_1m.sql

echo "SET GLOBAL autocommit=0;" >> t_user_1m.sql

echo "BEGIN;" >> t_user_1m.sql

for ((i=1000001; i<2000001; i++)); do
        echo "INSERT INTO t_user(id,name,create_time,password,nick) VALUES($i,'andy$i','2023-09-13 20:30:40','f6432274349b5cb93433f8ed886a3f37','石大大$i');" >> t_user_1m.sql
done

echo "COMMIT;" >> t_user_1m.sql

echo "SET GLOBAL autocommit=1;" >> t_user_1m.sql

echo "ALTER TABLE t_user ENABLE KEYS;" >> t_user_1m.sql

echo "SET GLOBAL sync_binlog=1;" >> t_user_1m.sql
echo "SET GLOBAL innodb_flush_log_at_timeout=1;" >> t_user_1m.sql
echo "SET GLOBAL innodb_flush_log_at_trx_commit=1;" >> t_user_1m.sql

echo 执行 t_user_1m.sql ......

time mysql -e "\. t_user_1m.sql" -h localhost -u root -pwinter winter

echo

date

echo

